### ISSUE TITLE
イースターエッグが表示されない不具合

### ISSUE THREAD

**Issue by hinaloe** [sudosan/Captter#8]
いなりは入ってなくていいけど閉じる方法もないやろ！

**Comment by sudosanet** [comment]
いなりをクリックすれば閉じれるんですがその

2015-02-27 23:40 GMT+09:00 Hinaloe notifications@github.com:

**Comment by sudosanet** [comment]
あ、でも重なってイースターエッグが表示されない不具合ありますね

**Comment by hinaloe** [comment]
それな
